---
# tasks file for php
- name: ajout du repo ondrej 
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: install php7
  apt: name={{ item }} state=present
  with_items:
    - python-apt
    - python-pycurl
    - php7.1-common
    - php7.1-cli
    - php7.1-dev
    - php7.1-gd
    - php7.1-curl
    - php7.1-json
    - php7.1-opcache
    - php7.1-xml
    - php7.1-mbstring
    - php7.1-pdo
    - php7.1-mysql
    - php-apcu
    - libapache2-mod-php7.1

